### ISSUE TITLE
Installing is bad

### ISSUE THREAD

**Issue by banshee** [pr0g/cmake-examples#2]
Generally, installing means you've made the local system and specific compiler for a project some sort of default.

This is bad.  Modern developers need to compile for multiple targets using multiple compilers and multiple versions of dependencies.  For example, what does it mean to "install" something like openssl when you want to use it for multiple versions of Android, iOS, your local machine, a Windows 7 desktop app, and some embedded system?  Even if you think you're just running on your local machine, you probably have several different versions of compilers you use - clang, gcc, some Microsoft thing, some other version of some Microsoft thing, etc.

Installing isn't a useful concept in 2019.  Build dependencies, always and everywhere.

**Comment by pmoulon** [comment]
Install is a target that the user is free to use or not.
CMake allows you to specify the install path, so you can easily compile for various target and have each version in different directories on a single machine according to the dev you are doing.

Install is still meaningful:
- for developers (experienced that know what they do, `make`, `make install in a specific dir`, then `find_package` to reuse it),
- for the hobbyist that want to access to your project, compile it and use it (no dev, `make install`).

**Comment by pr0g** [comment]
Hey @banshee!

You do make an excellent point when it comes to managing complex configurations as you describe - I have not attempted to address this in the examples (yet 😛). I would make one distinction though and that's installing _globally_ is perhaps not what you want in these more complex cases.

Up untill recently I think I thought pretty much the exact same as you. Every project I've ever worked on you usually have a specific folder called _external_ or _3rdParty_ which has all your libraries in with all the various configurations/versions etc. The concept of _installing_ did seem very perculiar to me.

The moment where I started to think this might be useful was after discovering `CMAKE_INSTALL_PREFIX` and `CMAKE_PREFIX_PATH` (what I believe @pmoulon was alluding to 🙂)

You use `CMAKE_INSTALL_PREFIX` when generating the CMake project in the build directory, here you can specify where you'd like to install the project (if you notice in my .gitignore file I've actually added _install/_ as well as _build/_, the idea being you install the project to an install folder in an _out of source_ kind of way) and then when you build the application, you pass `CMAKE_PREFIX_PATH` to the `cmake` command to look in that directory and find the installed library. This way you get the benefit of a nice bundled target without having to use it via `add_subdirectory` in your `CMakeLists.txt file`.

The other thing that's pretty cool about installing I only learned recently is you get this nice separation between private project structure and public project structure. Say in my library I have a bunch of folders scattered around, each with a random assortment of headers. Say I'd like to have my library be more easily usable by throwing all the headers under `include/<my_project>/header.h>`, so users can just `#include "<my_project>/header.h"` instead of some ugly include path that might be an implementation thing I don't want people to worry about.

Someone also mentioned to me there's a whole load of cool version stuff built into CMake you can use when installing libraries (locally or globally) which I totally ignored in the examples, I need to do some more research into this though as I haven't used it myself 🙈

I'll be adding more examples to flesh things out - please stay tuned :blush: - I may yet convice you installing is good, you never know :wink:

Thanks for the feedback!


Tom

**Comment by maluramichael** [comment]
It would be nice to have an example where you can install a library or at the same time just `ln -s` it to your `project/libs` directory and then use it with `add_subdirectory(libs/lib)`. Thats where iam struggle right now.

Would be cool to be that flexible. So one could install it and someone else just imports your library in his own project.

**Comment by pr0g** [comment]
Hey @maluramichael,

That is an interesting idea and if you look at the links on the main README, the articles by foonathan I believe have some examples of this.

My hesitation with doing this (and I could be wrong about this! 😬) is when you add an entirely separate library via `add_subdirectory`, everything in your parent `CMakeLists.txt` files are visible in the child `CMakeLists.txt` files - this means potentially if the library author hasn't correctly namespaced things you may get name collision or strange subtle bugs, or you might accidentally end up modifying a nested `CMakeLists.txt` to make it inadvertently depend on the _outer_ project.

I must admit you do have to be a bit paranoid to worry about these types of things, and 99% of the time it's probably going to be fine, but it's my opinion (as of this writing - I might change my mind in future 😛) that using an installed target is safer and more reliable.

I want to try and find a way to make the experience less clunky (and I believe vcpkg is one answer to such a problem) but don't have a solution yet. If I think of something cool I'll be sure to share it here 🙂 

I hope that makes some sense,

Cheers!


Tom

**Comment by maluramichael** [comment]
Just to clarify why i would like to have a libs directory for my own library: i would like to iterate faster while coding and i don't want to run `make install` everytime i change my lib slightly. Here is an example: https://github.com/maluramichael/cmake-test-application/blob/master/CMakeLists.txt

It would be awesome when my CMakeLists file looks the same for both cases.

Anyway great project here and thanks for the help.

**Comment by pr0g** [comment]
@maluramichael - ah I see understood. Yes a way of making it easy to update a library during development is a good point and one I haven't optimized for here - this is definitely something I'll have to have a think about and do some research on. I'll see if I can think of a good answer over the coming weeks 🙂 

I'm going to close this issue for now as it's not related to a specific problem with the repo, it's more philosophical in nature 😉 I appreciate the feedback though, I'll see if I can create some examples that make use of CMake versioning support (I know nothing about this yet so bare with me! 😄)

**Comment by pr0g** [comment]
Just a quick update on this - I've added a new example folder called [static-versioned](https://github.com/pr0g/cmake-examples/tree/master/examples/static-versioned) which contains an example of a being able to install multiple versions of the same library. It potentially isn't the most idiomatic way of doing it (I'm not sure), but from a functional point of view it could be quite useful. I'm still investigating/thinking about a way of making the iterations for library/app usage quicker 🙂. Cheers!

**Comment by pr0g** [comment]
Hey @maluramichael,

Quick update I thought you might be interested in; I've added a new example called [`static_auto_install`](https://github.com/pr0g/cmake-examples/tree/master/examples/more/static-auto-install) which is an attempt at answering the problem you had about the overhead of working on an application and library at the same time. 

I don't think it fully solves it (yet) but I think it shows promise and might potentially be useful for something 🙂 

Cheers!

**Comment by dbarbier** [comment]
Hello, you may also add an `export(EXPORT)` command in your library CMakeLists.txt so that its built tree can be imported.  In your application, run `cmake -D<MYLIB>_DIR=/path/to/lib/build`.

**Comment by pr0g** [comment]
Hello @dbarbier - interesting you mention this. I did at one point have the `export(EXPORT)` command in my `CMakeLists.txt` files but after speaking with Colby Pike (of [@vector_of_bool](https://twitter.com/vector_of_bool) fame), he advised against the practice.

> In general, I would recommend against using the `export()` command for this purpose. It's somewhat hairy and can cause confusion and fragile builds. Installing the exports file is preferred in almost all cases. Your current design looks fairly solid, so I'd recommend sticking with that.

This is why I've chosen not to use it. It's also possible so simply use `add_subdirectory` in many cases should people not wish to install.
